name: Snyk Security Scan

on:
  workflow_dispatch:
  push:
    branches:
    - "main"

jobs:
  build:
    uses: cohesive/cohesive_infra_github_actions/.github/workflows/snyk_base.yml@main
    secrets: inherit
