name: Snyk Security Scan

on:
  workflow_call:

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }} 
          
      - name: Install curl if not installed
        run: |
          if ! command -v curl &> /dev/null; then
            echo "curl not found, installing..."
            sudo apt-get update && sudo apt-get install -y curl
          else
            echo "curl is already installed."
          fi
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt
        continue-on-error: true

      - name: Set up Node.js (for Snyk)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install jq (latest version)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Snyk
        run: npm install -g snyk

      - name: Check if Dockerfile exists
        id: check_dockerfile
        run: |
          if [ -f Dockerfile ]; then
            echo "DOCKERFILE_FOUND=true" >> $GITHUB_ENV
          else
            echo "DOCKERFILE_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Import VNS3 Base Image
        if: env.DOCKERFILE_FOUND == 'true'
        run: |
          docker import  ${{ secrets.VNS3_BASE_IMAGE_URL }} vns3local:vns3_base
      
      - name: Build Docker Image
        if: env.DOCKERFILE_FOUND == 'true'
        run: docker build -t scancontainer .
        continue-on-error: true
      
      - name: Run Snyk Container Scan
        if: env.DOCKERFILE_FOUND == 'true'
        run: snyk container test scancontainer --json --exclude-base-image-vulns > snyk-results-container.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Package Manager Scan
        run: snyk test --all-projects --json > snyk-results-projects.json 
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan
        run: snyk code test --all-subdirectories --json > snyk-results-code.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Print Snyk Docker Vulerabilities
        if: env.DOCKERFILE_FOUND == 'true'
        run: cat snyk-results-container.json
        continue-on-error: true

      - name: Print Snyk Package Manager Vulerabilities
        run: cat snyk-results-projects.json
        continue-on-error: true

      - name: Print Snyk Code Vulerabilities
        run: cat snyk-results-code.json
        continue-on-error: true

      - name: Send Container Results to Slack
        if: env.DOCKERFILE_FOUND == 'true'
        run: |
          REPO_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.event.ref }}"
      
          if [ -f snyk-results-container.json ]; then
            # Stream vulnerabilities and create slack message
            vulnerabilities=$(jq -c '[.vulnerabilities[]? | {
              title: .title,
              package: .packageName, 
              version: .version, 
              severity: .severity, 
              description: (.identifiers.CVE // ["N/A"]) | join(", ")
            }] | map("*\(.title) (\(.package) v\(.version))*\nSeverity: \(.severity)\nDescription: \(.description)\n") | join("\n----------------\n")' snyk-results-container.json || echo "[]")
        
            if [[ -n "$(echo "$vulnerabilities" | xargs)" ]] && [ "$vulnerabilities" != "[]" ]; then
              slack_message=$(jq -n --argjson vulnerabilities "$vulnerabilities" --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("*Snyk detected container vulnerabilities in \($repo) [\($branch)]*\n" + $vulnerabilities)
              }')
            else
              slack_message=$(jq -n --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("✅ No container vulnerabilities found in \($repo) [\($branch)].")
              }')
            fi
          else
            slack_message=$(jq -n --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("✅ No container vulnerabilities found in \($repo) [\($branch)]")
              }')
          fi
          echo $slack_message
          # Send the Slack message
          curl -X POST -H "Content-type: application/json" --data "$slack_message" ${{ secrets.SECURITY_BOTS_SLACK_URL }}
        continue-on-error: true

      - name: Send Package Manager Results to Slack
        run: |
          REPO_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.event.ref }}"
          
          if [ -f snyk-results-projects.json ]; then
            # Stream vulnerabilities and create slack message
            vulnerabilities=$(jq -c '[.vulnerabilities[]? | select(.version | test("ubuntu"; "i") | not) | {
              title: .title,
              package: .packageName, 
              version: .version, 
              severity: .severity, 
              description: (.identifiers.CVE // ["N/A"]) | join(", ")
            }] | map("*\(.title) (\(.package) v\(.version))*\nSeverity: \(.severity)\nDescription: \(.description)\n") | join("\n----------------\n")' snyk-results-projects.json || echo "[]")
            echo "vul:$vulnerabilities"
            if [[ -n "$(echo "$vulnerabilities" | xargs)" ]] && [ "$vulnerabilities" != "[]" ]; then
              slack_message=$(jq -n --argjson vulnerabilities "$vulnerabilities" --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("*Snyk detected package manager vulnerabilities in \($repo) [\($branch)]*\n" + $vulnerabilities)
              }')
            else
              slack_message=$(jq -n --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("✅ No package manager vulnerabilities found in \($repo) [\($branch)].")
              }')
            fi
          else
            slack_message=$(jq -n --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("✅ No package manager vulnerabilities found in \($repo) [\($branch)]")
              }')
          fi
      
          # Send the Slack message
          curl -X POST -H "Content-type: application/json" --data "$slack_message" ${{ secrets.SECURITY_BOTS_SLACK_URL }}
        continue-on-error: true

      - name: Send Code Results to Slack
        run: |
          REPO_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.event.ref }}"
      
          if [ -f snyk-results-code.json ] && ! grep -q "NoSupportedSastFiles" snyk-results-code.json; then
            vulnerabilities=$(jq -c '[.runs[].results[] | {
              ruleId: .ruleId,
              level: .level,
              message: .message.text,
              location: .locations[0].physicalLocation.artifactLocation.uri,
              line: .locations[0].physicalLocation.region.startLine
            }] | map("*\(.ruleId)*\nLevel: \(.level)\nMessage: \(.message)\nLocation: \(.location)\nLine: \(.line)*") | join("\n----------------\n")' snyk-results-code.json || echo "[]")
      
            if [[ -n "$(echo "$vulnerabilities" | xargs)" ]] && [ "$vulnerabilities" != "[]" ]; then
              slack_message=$(jq -n --argjson vulnerabilities "$vulnerabilities" --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("*Snyk detected code vulnerabilities in \($repo) [\($branch)]*\n" + $vulnerabilities)
              }')
            else
              slack_message="✅ No code vulnerabilities found in *$REPO_NAME* [$BRANCH_NAME]."
            fi
          else
            slack_message=$(jq -n --arg repo "$REPO_NAME" --arg branch "$BRANCH_NAME" '{
                text: ("✅ No code vulnerabilities found in \($repo) [\($branch)]")
              }')
          fi
      
          # Send the Slack message
          curl -X POST -H "Content-type: application/json" --data "$slack_message" ${{ secrets.SECURITY_BOTS_SLACK_URL }}
        continue-on-error: true
